// Code generated by protoc-gen-go. DO NOT EDIT.
// source: profile.proto

package profile

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StatusCode int32

const (
	StatusCode_Unknown StatusCode = 0
	StatusCode_OK      StatusCode = 1
	StatusCode_Failed  StatusCode = 2
)

var StatusCode_name = map[int32]string{
	0: "Unknown",
	1: "OK",
	2: "Failed",
}

var StatusCode_value = map[string]int32{
	"Unknown": 0,
	"OK":      1,
	"Failed":  2,
}

func (x StatusCode) String() string {
	return proto.EnumName(StatusCode_name, int32(x))
}

func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{0}
}

type FileChunk struct {
	Content              []byte   `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileChunk) Reset()         { *m = FileChunk{} }
func (m *FileChunk) String() string { return proto.CompactTextString(m) }
func (*FileChunk) ProtoMessage()    {}
func (*FileChunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{0}
}

func (m *FileChunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileChunk.Unmarshal(m, b)
}
func (m *FileChunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileChunk.Marshal(b, m, deterministic)
}
func (m *FileChunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileChunk.Merge(m, src)
}
func (m *FileChunk) XXX_Size() int {
	return xxx_messageInfo_FileChunk.Size(m)
}
func (m *FileChunk) XXX_DiscardUnknown() {
	xxx_messageInfo_FileChunk.DiscardUnknown(m)
}

var xxx_messageInfo_FileChunk proto.InternalMessageInfo

func (m *FileChunk) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type Status struct {
	Code                 StatusCode `protobuf:"varint,1,opt,name=Code,proto3,enum=profile.StatusCode" json:"Code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{1}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() StatusCode {
	if m != nil {
		return m.Code
	}
	return StatusCode_Unknown
}

type Rate struct {
	Value                int64    `protobuf:"varint,1,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rate) Reset()         { *m = Rate{} }
func (m *Rate) String() string { return proto.CompactTextString(m) }
func (*Rate) ProtoMessage()    {}
func (*Rate) Descriptor() ([]byte, []int) {
	return fileDescriptor_744bf7a47b381504, []int{2}
}

func (m *Rate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rate.Unmarshal(m, b)
}
func (m *Rate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rate.Marshal(b, m, deterministic)
}
func (m *Rate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rate.Merge(m, src)
}
func (m *Rate) XXX_Size() int {
	return xxx_messageInfo_Rate.Size(m)
}
func (m *Rate) XXX_DiscardUnknown() {
	xxx_messageInfo_Rate.DiscardUnknown(m)
}

var xxx_messageInfo_Rate proto.InternalMessageInfo

func (m *Rate) GetValue() int64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterEnum("profile.StatusCode", StatusCode_name, StatusCode_value)
	proto.RegisterType((*FileChunk)(nil), "profile.FileChunk")
	proto.RegisterType((*Status)(nil), "profile.Status")
	proto.RegisterType((*Rate)(nil), "profile.Rate")
}

func init() {
	proto.RegisterFile("profile.proto", fileDescriptor_744bf7a47b381504)
}

var fileDescriptor_744bf7a47b381504 = []byte{
	// 433 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x5b, 0x6f, 0xd3, 0x40,
	0x10, 0x85, 0xe3, 0xb6, 0xb1, 0xc9, 0xf4, 0x42, 0xba, 0xe1, 0xd2, 0x06, 0x84, 0x90, 0x25, 0x04,
	0x42, 0xc2, 0x85, 0x54, 0x80, 0x68, 0x25, 0x84, 0xe2, 0x62, 0x1e, 0x50, 0x45, 0x65, 0xb7, 0x3c,
	0xf0, 0xb6, 0xb5, 0x27, 0x89, 0x95, 0xcd, 0x6e, 0xb4, 0x59, 0x13, 0xf2, 0x0f, 0xf8, 0xd9, 0xc8,
	0xbb, 0x4e, 0x90, 0x72, 0x41, 0xec, 0xe3, 0xec, 0xcc, 0x77, 0xe6, 0x9c, 0x91, 0x0d, 0xfb, 0x63,
	0x29, 0x7a, 0x39, 0xc3, 0x60, 0x2c, 0x85, 0x12, 0xc4, 0xab, 0xca, 0xf6, 0x93, 0xbe, 0x10, 0x7d,
	0x86, 0x27, 0xfa, 0xf9, 0xb6, 0xe8, 0x9d, 0x64, 0x85, 0xa4, 0x2a, 0x17, 0xdc, 0x0c, 0xb6, 0x1f,
	0x2d, 0xf7, 0x71, 0x34, 0x56, 0x33, 0xd3, 0xf4, 0x9f, 0x41, 0x23, 0xca, 0x19, 0x86, 0x83, 0x82,
	0x0f, 0xc9, 0x11, 0x78, 0xa1, 0xe0, 0x0a, 0xb9, 0x3a, 0x72, 0x9e, 0x3a, 0x2f, 0xf6, 0xe2, 0x79,
	0xe9, 0xbf, 0x01, 0x37, 0x51, 0x54, 0x15, 0x13, 0xf2, 0x1c, 0x76, 0x42, 0x91, 0xa1, 0x1e, 0x38,
	0xe8, 0xb4, 0x82, 0xb9, 0x29, 0xd3, 0x2e, 0x5b, 0xb1, 0x1e, 0xf0, 0x1f, 0xc3, 0x4e, 0x4c, 0x15,
	0x92, 0x7b, 0x50, 0xff, 0x4e, 0x59, 0x61, 0x88, 0xed, 0xd8, 0x14, 0x2f, 0x5f, 0x01, 0xfc, 0x25,
	0xc8, 0x2e, 0x78, 0x37, 0x7c, 0xc8, 0xc5, 0x94, 0x37, 0x6b, 0xc4, 0x85, 0xad, 0x6f, 0x5f, 0x9b,
	0x0e, 0x01, 0x70, 0x23, 0x9a, 0x33, 0xcc, 0x9a, 0x5b, 0x9d, 0xdf, 0x1e, 0x1c, 0x5c, 0x99, 0x4d,
	0x09, 0xca, 0x9f, 0x79, 0x8a, 0xe4, 0x23, 0x1c, 0x86, 0x0c, 0xa9, 0xac, 0x9e, 0x43, 0x9a, 0x0e,
	0x90, 0x3c, 0x08, 0x4c, 0xd8, 0x60, 0x1e, 0x36, 0xf8, 0x5c, 0x86, 0x6d, 0xdf, 0x5d, 0xf2, 0xe9,
	0xd7, 0xc8, 0x5b, 0x38, 0x4c, 0x50, 0x5d, 0xe2, 0xa8, 0x12, 0xd0, 0x66, 0xf7, 0x17, 0x73, 0x65,
	0xb9, 0x0e, 0x3b, 0x87, 0x87, 0x25, 0x56, 0x28, 0xfc, 0x55, 0x81, 0x91, 0xa4, 0x69, 0x79, 0xee,
	0xff, 0x80, 0xdf, 0x43, 0x2b, 0x41, 0xd5, 0x65, 0x22, 0x1d, 0xda, 0x6d, 0xfd, 0x04, 0xad, 0x18,
	0x27, 0x2b, 0x76, 0x2d, 0xe2, 0x46, 0x70, 0x6c, 0x14, 0xd6, 0x39, 0xb7, 0xd0, 0xe9, 0xc2, 0x7d,
	0xad, 0xb3, 0x12, 0xc2, 0x42, 0xe3, 0x14, 0xb6, 0xc3, 0xab, 0x1b, 0x72, 0xbc, 0x42, 0x5c, 0x54,
	0x5f, 0xee, 0x7a, 0xc8, 0xbd, 0xc4, 0x91, 0x90, 0x33, 0x9b, 0x4d, 0x1d, 0xa8, 0xeb, 0xc0, 0x96,
	0x8c, 0x0e, 0x67, 0xc3, 0x7c, 0x80, 0xbd, 0xeb, 0x81, 0x44, 0x9a, 0x85, 0x12, 0x2d, 0x8f, 0xf1,
	0x0e, 0x1a, 0x5f, 0x44, 0x2c, 0x0a, 0x95, 0x73, 0x2b, 0xee, 0x0c, 0xea, 0xd7, 0x92, 0xa6, 0xf8,
	0xaf, 0x33, 0x92, 0x05, 0xb6, 0xf8, 0xc9, 0xfd, 0xda, 0x6b, 0x87, 0x9c, 0xc1, 0x9d, 0x0b, 0x31,
	0xe5, 0x4c, 0xd0, 0x6c, 0xe3, 0xca, 0x0d, 0x6c, 0x77, 0xf7, 0x47, 0x23, 0x38, 0xaf, 0x5a, 0xb7,
	0xae, 0x86, 0x4e, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x55, 0xf2, 0xca, 0x5e, 0x9c, 0x04, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProfileServiceClient is the client API for ProfileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProfileServiceClient interface {
	ClearProfileCache(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Status, error)
	SetMemProfileRate(ctx context.Context, in *Rate, opts ...grpc.CallOption) (*Status, error)
	SetMutexProfileFraction(ctx context.Context, in *Rate, opts ...grpc.CallOption) (*Status, error)
	SetBlockProfileRate(ctx context.Context, in *Rate, opts ...grpc.CallOption) (*Status, error)
	ResetMemProfileRate(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Status, error)
	ResetMutexProfileFraction(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Status, error)
	ResetBlockProfileRate(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Status, error)
	CPU(ctx context.Context, in *duration.Duration, opts ...grpc.CallOption) (*Status, error)
	Memory(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Status, error)
	Mutex(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Status, error)
	Block(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Status, error)
	ThreadCreate(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Status, error)
	GoRoutine(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Status, error)
	Trace(ctx context.Context, in *duration.Duration, opts ...grpc.CallOption) (ProfileService_TraceClient, error)
	Download(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (ProfileService_DownloadClient, error)
}

type profileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProfileServiceClient(cc grpc.ClientConnInterface) ProfileServiceClient {
	return &profileServiceClient{cc}
}

func (c *profileServiceClient) ClearProfileCache(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/profile.ProfileService/ClearProfileCache", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) SetMemProfileRate(ctx context.Context, in *Rate, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/profile.ProfileService/SetMemProfileRate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) SetMutexProfileFraction(ctx context.Context, in *Rate, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/profile.ProfileService/SetMutexProfileFraction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) SetBlockProfileRate(ctx context.Context, in *Rate, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/profile.ProfileService/SetBlockProfileRate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) ResetMemProfileRate(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/profile.ProfileService/ResetMemProfileRate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) ResetMutexProfileFraction(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/profile.ProfileService/ResetMutexProfileFraction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) ResetBlockProfileRate(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/profile.ProfileService/ResetBlockProfileRate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) CPU(ctx context.Context, in *duration.Duration, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/profile.ProfileService/CPU", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) Memory(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/profile.ProfileService/Memory", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) Mutex(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/profile.ProfileService/Mutex", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) Block(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/profile.ProfileService/Block", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) ThreadCreate(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/profile.ProfileService/ThreadCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) GoRoutine(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := c.cc.Invoke(ctx, "/profile.ProfileService/GoRoutine", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) Trace(ctx context.Context, in *duration.Duration, opts ...grpc.CallOption) (ProfileService_TraceClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ProfileService_serviceDesc.Streams[0], "/profile.ProfileService/Trace", opts...)
	if err != nil {
		return nil, err
	}
	x := &profileServiceTraceClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ProfileService_TraceClient interface {
	Recv() (*FileChunk, error)
	grpc.ClientStream
}

type profileServiceTraceClient struct {
	grpc.ClientStream
}

func (x *profileServiceTraceClient) Recv() (*FileChunk, error) {
	m := new(FileChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *profileServiceClient) Download(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (ProfileService_DownloadClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ProfileService_serviceDesc.Streams[1], "/profile.ProfileService/Download", opts...)
	if err != nil {
		return nil, err
	}
	x := &profileServiceDownloadClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ProfileService_DownloadClient interface {
	Recv() (*FileChunk, error)
	grpc.ClientStream
}

type profileServiceDownloadClient struct {
	grpc.ClientStream
}

func (x *profileServiceDownloadClient) Recv() (*FileChunk, error) {
	m := new(FileChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ProfileServiceServer is the server API for ProfileService service.
type ProfileServiceServer interface {
	ClearProfileCache(context.Context, *empty.Empty) (*Status, error)
	SetMemProfileRate(context.Context, *Rate) (*Status, error)
	SetMutexProfileFraction(context.Context, *Rate) (*Status, error)
	SetBlockProfileRate(context.Context, *Rate) (*Status, error)
	ResetMemProfileRate(context.Context, *empty.Empty) (*Status, error)
	ResetMutexProfileFraction(context.Context, *empty.Empty) (*Status, error)
	ResetBlockProfileRate(context.Context, *empty.Empty) (*Status, error)
	CPU(context.Context, *duration.Duration) (*Status, error)
	Memory(context.Context, *empty.Empty) (*Status, error)
	Mutex(context.Context, *empty.Empty) (*Status, error)
	Block(context.Context, *empty.Empty) (*Status, error)
	ThreadCreate(context.Context, *empty.Empty) (*Status, error)
	GoRoutine(context.Context, *empty.Empty) (*Status, error)
	Trace(*duration.Duration, ProfileService_TraceServer) error
	Download(*empty.Empty, ProfileService_DownloadServer) error
}

// UnimplementedProfileServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProfileServiceServer struct {
}

func (*UnimplementedProfileServiceServer) ClearProfileCache(ctx context.Context, req *empty.Empty) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearProfileCache not implemented")
}
func (*UnimplementedProfileServiceServer) SetMemProfileRate(ctx context.Context, req *Rate) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetMemProfileRate not implemented")
}
func (*UnimplementedProfileServiceServer) SetMutexProfileFraction(ctx context.Context, req *Rate) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetMutexProfileFraction not implemented")
}
func (*UnimplementedProfileServiceServer) SetBlockProfileRate(ctx context.Context, req *Rate) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetBlockProfileRate not implemented")
}
func (*UnimplementedProfileServiceServer) ResetMemProfileRate(ctx context.Context, req *empty.Empty) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetMemProfileRate not implemented")
}
func (*UnimplementedProfileServiceServer) ResetMutexProfileFraction(ctx context.Context, req *empty.Empty) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetMutexProfileFraction not implemented")
}
func (*UnimplementedProfileServiceServer) ResetBlockProfileRate(ctx context.Context, req *empty.Empty) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetBlockProfileRate not implemented")
}
func (*UnimplementedProfileServiceServer) CPU(ctx context.Context, req *duration.Duration) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CPU not implemented")
}
func (*UnimplementedProfileServiceServer) Memory(ctx context.Context, req *empty.Empty) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Memory not implemented")
}
func (*UnimplementedProfileServiceServer) Mutex(ctx context.Context, req *empty.Empty) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Mutex not implemented")
}
func (*UnimplementedProfileServiceServer) Block(ctx context.Context, req *empty.Empty) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Block not implemented")
}
func (*UnimplementedProfileServiceServer) ThreadCreate(ctx context.Context, req *empty.Empty) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ThreadCreate not implemented")
}
func (*UnimplementedProfileServiceServer) GoRoutine(ctx context.Context, req *empty.Empty) (*Status, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GoRoutine not implemented")
}
func (*UnimplementedProfileServiceServer) Trace(req *duration.Duration, srv ProfileService_TraceServer) error {
	return status.Errorf(codes.Unimplemented, "method Trace not implemented")
}
func (*UnimplementedProfileServiceServer) Download(req *empty.Empty, srv ProfileService_DownloadServer) error {
	return status.Errorf(codes.Unimplemented, "method Download not implemented")
}

func RegisterProfileServiceServer(s *grpc.Server, srv ProfileServiceServer) {
	s.RegisterService(&_ProfileService_serviceDesc, srv)
}

func _ProfileService_ClearProfileCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).ClearProfileCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.ProfileService/ClearProfileCache",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).ClearProfileCache(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_SetMemProfileRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Rate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).SetMemProfileRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.ProfileService/SetMemProfileRate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).SetMemProfileRate(ctx, req.(*Rate))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_SetMutexProfileFraction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Rate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).SetMutexProfileFraction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.ProfileService/SetMutexProfileFraction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).SetMutexProfileFraction(ctx, req.(*Rate))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_SetBlockProfileRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Rate)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).SetBlockProfileRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.ProfileService/SetBlockProfileRate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).SetBlockProfileRate(ctx, req.(*Rate))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_ResetMemProfileRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).ResetMemProfileRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.ProfileService/ResetMemProfileRate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).ResetMemProfileRate(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_ResetMutexProfileFraction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).ResetMutexProfileFraction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.ProfileService/ResetMutexProfileFraction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).ResetMutexProfileFraction(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_ResetBlockProfileRate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).ResetBlockProfileRate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.ProfileService/ResetBlockProfileRate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).ResetBlockProfileRate(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_CPU_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(duration.Duration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).CPU(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.ProfileService/CPU",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).CPU(ctx, req.(*duration.Duration))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_Memory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).Memory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.ProfileService/Memory",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).Memory(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_Mutex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).Mutex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.ProfileService/Mutex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).Mutex(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_Block_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).Block(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.ProfileService/Block",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).Block(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_ThreadCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).ThreadCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.ProfileService/ThreadCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).ThreadCreate(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_GoRoutine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).GoRoutine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/profile.ProfileService/GoRoutine",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).GoRoutine(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_Trace_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(duration.Duration)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProfileServiceServer).Trace(m, &profileServiceTraceServer{stream})
}

type ProfileService_TraceServer interface {
	Send(*FileChunk) error
	grpc.ServerStream
}

type profileServiceTraceServer struct {
	grpc.ServerStream
}

func (x *profileServiceTraceServer) Send(m *FileChunk) error {
	return x.ServerStream.SendMsg(m)
}

func _ProfileService_Download_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProfileServiceServer).Download(m, &profileServiceDownloadServer{stream})
}

type ProfileService_DownloadServer interface {
	Send(*FileChunk) error
	grpc.ServerStream
}

type profileServiceDownloadServer struct {
	grpc.ServerStream
}

func (x *profileServiceDownloadServer) Send(m *FileChunk) error {
	return x.ServerStream.SendMsg(m)
}

var _ProfileService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "profile.ProfileService",
	HandlerType: (*ProfileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClearProfileCache",
			Handler:    _ProfileService_ClearProfileCache_Handler,
		},
		{
			MethodName: "SetMemProfileRate",
			Handler:    _ProfileService_SetMemProfileRate_Handler,
		},
		{
			MethodName: "SetMutexProfileFraction",
			Handler:    _ProfileService_SetMutexProfileFraction_Handler,
		},
		{
			MethodName: "SetBlockProfileRate",
			Handler:    _ProfileService_SetBlockProfileRate_Handler,
		},
		{
			MethodName: "ResetMemProfileRate",
			Handler:    _ProfileService_ResetMemProfileRate_Handler,
		},
		{
			MethodName: "ResetMutexProfileFraction",
			Handler:    _ProfileService_ResetMutexProfileFraction_Handler,
		},
		{
			MethodName: "ResetBlockProfileRate",
			Handler:    _ProfileService_ResetBlockProfileRate_Handler,
		},
		{
			MethodName: "CPU",
			Handler:    _ProfileService_CPU_Handler,
		},
		{
			MethodName: "Memory",
			Handler:    _ProfileService_Memory_Handler,
		},
		{
			MethodName: "Mutex",
			Handler:    _ProfileService_Mutex_Handler,
		},
		{
			MethodName: "Block",
			Handler:    _ProfileService_Block_Handler,
		},
		{
			MethodName: "ThreadCreate",
			Handler:    _ProfileService_ThreadCreate_Handler,
		},
		{
			MethodName: "GoRoutine",
			Handler:    _ProfileService_GoRoutine_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Trace",
			Handler:       _ProfileService_Trace_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Download",
			Handler:       _ProfileService_Download_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "profile.proto",
}
