// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.7.1
// source: profile.proto

package proto

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	duration "github.com/golang/protobuf/ptypes/duration"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type ProfileVariable int32

const (
	ProfileVariable_MemProfileRate       ProfileVariable = 0
	ProfileVariable_MutexProfileFraction ProfileVariable = 1
	ProfileVariable_BlockProfileRate     ProfileVariable = 2
)

// Enum value maps for ProfileVariable.
var (
	ProfileVariable_name = map[int32]string{
		0: "MemProfileRate",
		1: "MutexProfileFraction",
		2: "BlockProfileRate",
	}
	ProfileVariable_value = map[string]int32{
		"MemProfileRate":       0,
		"MutexProfileFraction": 1,
		"BlockProfileRate":     2,
	}
)

func (x ProfileVariable) Enum() *ProfileVariable {
	p := new(ProfileVariable)
	*p = x
	return p
}

func (x ProfileVariable) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProfileVariable) Descriptor() protoreflect.EnumDescriptor {
	return file_profile_proto_enumTypes[0].Descriptor()
}

func (ProfileVariable) Type() protoreflect.EnumType {
	return &file_profile_proto_enumTypes[0]
}

func (x ProfileVariable) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProfileVariable.Descriptor instead.
func (ProfileVariable) EnumDescriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{0}
}

type LookupProfile int32

const (
	LookupProfile_profileTypeHeap         LookupProfile = 0
	LookupProfile_profileTypeMutex        LookupProfile = 1
	LookupProfile_profileTypeBlock        LookupProfile = 2
	LookupProfile_profileTypeThreadCreate LookupProfile = 3
	LookupProfile_profileTypeGoRoutine    LookupProfile = 4
)

// Enum value maps for LookupProfile.
var (
	LookupProfile_name = map[int32]string{
		0: "profileTypeHeap",
		1: "profileTypeMutex",
		2: "profileTypeBlock",
		3: "profileTypeThreadCreate",
		4: "profileTypeGoRoutine",
	}
	LookupProfile_value = map[string]int32{
		"profileTypeHeap":         0,
		"profileTypeMutex":        1,
		"profileTypeBlock":        2,
		"profileTypeThreadCreate": 3,
		"profileTypeGoRoutine":    4,
	}
)

func (x LookupProfile) Enum() *LookupProfile {
	p := new(LookupProfile)
	*p = x
	return p
}

func (x LookupProfile) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LookupProfile) Descriptor() protoreflect.EnumDescriptor {
	return file_profile_proto_enumTypes[1].Descriptor()
}

func (LookupProfile) Type() protoreflect.EnumType {
	return &file_profile_proto_enumTypes[1]
}

func (x LookupProfile) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LookupProfile.Descriptor instead.
func (LookupProfile) EnumDescriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{1}
}

type NonLookupProfile int32

const (
	NonLookupProfile_profileTypeCPU   NonLookupProfile = 0
	NonLookupProfile_profileTypeTrace NonLookupProfile = 1
)

// Enum value maps for NonLookupProfile.
var (
	NonLookupProfile_name = map[int32]string{
		0: "profileTypeCPU",
		1: "profileTypeTrace",
	}
	NonLookupProfile_value = map[string]int32{
		"profileTypeCPU":   0,
		"profileTypeTrace": 1,
	}
)

func (x NonLookupProfile) Enum() *NonLookupProfile {
	p := new(NonLookupProfile)
	*p = x
	return p
}

func (x NonLookupProfile) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NonLookupProfile) Descriptor() protoreflect.EnumDescriptor {
	return file_profile_proto_enumTypes[2].Descriptor()
}

func (NonLookupProfile) Type() protoreflect.EnumType {
	return &file_profile_proto_enumTypes[2]
}

func (x NonLookupProfile) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NonLookupProfile.Descriptor instead.
func (NonLookupProfile) EnumDescriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{2}
}

type FileChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content []byte `protobuf:"bytes,1,opt,name=Content,proto3" json:"Content,omitempty"`
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_profile_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{0}
}

func (x *FileChunk) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

type StringType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (x *StringType) Reset() {
	*x = StringType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_profile_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringType) ProtoMessage() {}

func (x *StringType) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringType.ProtoReflect.Descriptor instead.
func (*StringType) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{1}
}

func (x *StringType) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LookupProfileType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Profile LookupProfile `protobuf:"varint,1,opt,name=Profile,proto3,enum=proto.LookupProfile" json:"Profile,omitempty"`
}

func (x *LookupProfileType) Reset() {
	*x = LookupProfileType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_profile_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookupProfileType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupProfileType) ProtoMessage() {}

func (x *LookupProfileType) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupProfileType.ProtoReflect.Descriptor instead.
func (*LookupProfileType) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{2}
}

func (x *LookupProfileType) GetProfile() LookupProfile {
	if x != nil {
		return x.Profile
	}
	return LookupProfile_profileTypeHeap
}

type NonLookupProfileType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Profile NonLookupProfile `protobuf:"varint,1,opt,name=Profile,proto3,enum=proto.NonLookupProfile" json:"Profile,omitempty"`
}

func (x *NonLookupProfileType) Reset() {
	*x = NonLookupProfileType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_profile_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NonLookupProfileType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NonLookupProfileType) ProtoMessage() {}

func (x *NonLookupProfileType) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NonLookupProfileType.ProtoReflect.Descriptor instead.
func (*NonLookupProfileType) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{3}
}

func (x *NonLookupProfileType) GetProfile() NonLookupProfile {
	if x != nil {
		return x.Profile
	}
	return NonLookupProfile_profileTypeCPU
}

type SetProfileInputType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Variable ProfileVariable `protobuf:"varint,1,opt,name=Variable,proto3,enum=proto.ProfileVariable" json:"Variable,omitempty"`
	Rate     int32           `protobuf:"varint,2,opt,name=Rate,proto3" json:"Rate,omitempty"`
}

func (x *SetProfileInputType) Reset() {
	*x = SetProfileInputType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_profile_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetProfileInputType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetProfileInputType) ProtoMessage() {}

func (x *SetProfileInputType) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetProfileInputType.ProtoReflect.Descriptor instead.
func (*SetProfileInputType) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{4}
}

func (x *SetProfileInputType) GetVariable() ProfileVariable {
	if x != nil {
		return x.Variable
	}
	return ProfileVariable_MemProfileRate
}

func (x *SetProfileInputType) GetRate() int32 {
	if x != nil {
		return x.Rate
	}
	return 0
}

type ResetProfileInputType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Variable ProfileVariable `protobuf:"varint,1,opt,name=Variable,proto3,enum=proto.ProfileVariable" json:"Variable,omitempty"`
}

func (x *ResetProfileInputType) Reset() {
	*x = ResetProfileInputType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_profile_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResetProfileInputType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetProfileInputType) ProtoMessage() {}

func (x *ResetProfileInputType) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetProfileInputType.ProtoReflect.Descriptor instead.
func (*ResetProfileInputType) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{5}
}

func (x *ResetProfileInputType) GetVariable() ProfileVariable {
	if x != nil {
		return x.Variable
	}
	return ProfileVariable_MemProfileRate
}

type LookupProfileInputType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProfileType LookupProfile `protobuf:"varint,1,opt,name=ProfileType,proto3,enum=proto.LookupProfile" json:"ProfileType,omitempty"`
	Keep        bool          `protobuf:"varint,2,opt,name=Keep,proto3" json:"Keep,omitempty"`
}

func (x *LookupProfileInputType) Reset() {
	*x = LookupProfileInputType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_profile_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LookupProfileInputType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupProfileInputType) ProtoMessage() {}

func (x *LookupProfileInputType) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupProfileInputType.ProtoReflect.Descriptor instead.
func (*LookupProfileInputType) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{6}
}

func (x *LookupProfileInputType) GetProfileType() LookupProfile {
	if x != nil {
		return x.ProfileType
	}
	return LookupProfile_profileTypeHeap
}

func (x *LookupProfileInputType) GetKeep() bool {
	if x != nil {
		return x.Keep
	}
	return false
}

type NonLookupProfileInputType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProfileType       NonLookupProfile   `protobuf:"varint,1,opt,name=ProfileType,proto3,enum=proto.NonLookupProfile" json:"ProfileType,omitempty"`
	Duration          *duration.Duration `protobuf:"bytes,2,opt,name=Duration,proto3" json:"Duration,omitempty"`
	WaitForCompletion bool               `protobuf:"varint,3,opt,name=WaitForCompletion,proto3" json:"WaitForCompletion,omitempty"`
	Keep              bool               `protobuf:"varint,4,opt,name=Keep,proto3" json:"Keep,omitempty"`
}

func (x *NonLookupProfileInputType) Reset() {
	*x = NonLookupProfileInputType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_profile_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NonLookupProfileInputType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NonLookupProfileInputType) ProtoMessage() {}

func (x *NonLookupProfileInputType) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NonLookupProfileInputType.ProtoReflect.Descriptor instead.
func (*NonLookupProfileInputType) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{7}
}

func (x *NonLookupProfileInputType) GetProfileType() NonLookupProfile {
	if x != nil {
		return x.ProfileType
	}
	return NonLookupProfile_profileTypeCPU
}

func (x *NonLookupProfileInputType) GetDuration() *duration.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *NonLookupProfileInputType) GetWaitForCompletion() bool {
	if x != nil {
		return x.WaitForCompletion
	}
	return false
}

func (x *NonLookupProfileInputType) GetKeep() bool {
	if x != nil {
		return x.Keep
	}
	return false
}

var File_profile_proto protoreflect.FileDescriptor

var file_profile_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x25, 0x0a, 0x09, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b,
	0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x26, 0x0a, 0x0a, 0x53, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x43, 0x0a, 0x11, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x50, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x2e, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x07,
	0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x22, 0x49, 0x0a, 0x14, 0x4e, 0x6f, 0x6e, 0x4c, 0x6f,
	0x6f, 0x6b, 0x75, 0x70, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x31, 0x0a, 0x07, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x6f, 0x6e, 0x4c, 0x6f, 0x6f, 0x6b,
	0x75, 0x70, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x07, 0x50, 0x72, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x22, 0x5d, 0x0a, 0x13, 0x53, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x49, 0x6e, 0x70, 0x75, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x32, 0x0a, 0x08, 0x56, 0x61, 0x72,
	0x69, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x56, 0x61, 0x72, 0x69, 0x61,
	0x62, 0x6c, 0x65, 0x52, 0x08, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x52, 0x61, 0x74, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x52, 0x61, 0x74,
	0x65, 0x22, 0x4b, 0x0a, 0x15, 0x52, 0x65, 0x73, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x32, 0x0a, 0x08, 0x56, 0x61,
	0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x16, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x56, 0x61, 0x72, 0x69,
	0x61, 0x62, 0x6c, 0x65, 0x52, 0x08, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x22, 0x64,
	0x0a, 0x16, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x49,
	0x6e, 0x70, 0x75, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x36, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x50, 0x72, 0x6f, 0x66,
	0x69, 0x6c, 0x65, 0x52, 0x0b, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x12, 0x0a, 0x04, 0x4b, 0x65, 0x65, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04,
	0x4b, 0x65, 0x65, 0x70, 0x22, 0xcf, 0x01, 0x0a, 0x19, 0x4e, 0x6f, 0x6e, 0x4c, 0x6f, 0x6f, 0x6b,
	0x75, 0x70, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x39, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x17, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x4e, 0x6f, 0x6e, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x52, 0x0b, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x35, 0x0a,
	0x08, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x44, 0x75, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x08, 0x44, 0x75, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2c, 0x0a, 0x11, 0x57, 0x61, 0x69, 0x74, 0x46, 0x6f, 0x72, 0x43,
	0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x11, 0x57, 0x61, 0x69, 0x74, 0x46, 0x6f, 0x72, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x4b, 0x65, 0x65, 0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x04, 0x4b, 0x65, 0x65, 0x70, 0x2a, 0x55, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x56, 0x61, 0x72, 0x69, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x0e, 0x4d, 0x65, 0x6d,
	0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x61, 0x74, 0x65, 0x10, 0x00, 0x12, 0x18, 0x0a,
	0x14, 0x4d, 0x75, 0x74, 0x65, 0x78, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x46, 0x72, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x42, 0x6c, 0x6f, 0x63, 0x6b,
	0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x52, 0x61, 0x74, 0x65, 0x10, 0x02, 0x2a, 0x87, 0x01,
	0x0a, 0x0d, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12,
	0x13, 0x0a, 0x0f, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x48, 0x65,
	0x61, 0x70, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x4d, 0x75, 0x74, 0x65, 0x78, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x70, 0x72,
	0x6f, 0x66, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x10, 0x02,
	0x12, 0x1b, 0x0a, 0x17, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x54,
	0x68, 0x72, 0x65, 0x61, 0x64, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x10, 0x03, 0x12, 0x18, 0x0a,
	0x14, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x47, 0x6f, 0x52, 0x6f,
	0x75, 0x74, 0x69, 0x6e, 0x65, 0x10, 0x04, 0x2a, 0x3c, 0x0a, 0x10, 0x4e, 0x6f, 0x6e, 0x4c, 0x6f,
	0x6f, 0x6b, 0x75, 0x70, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x0e, 0x70,
	0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x43, 0x50, 0x55, 0x10, 0x00, 0x12,
	0x14, 0x0a, 0x10, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x54, 0x72,
	0x61, 0x63, 0x65, 0x10, 0x01, 0x32, 0xf1, 0x04, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x31, 0x0a, 0x04, 0x50, 0x69, 0x6e, 0x67,
	0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x43, 0x0a, 0x11, 0x43,
	0x6c, 0x65, 0x61, 0x72, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x43, 0x61, 0x63, 0x68, 0x65,
	0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79,
	0x12, 0x39, 0x0a, 0x03, 0x53, 0x65, 0x74, 0x12, 0x1a, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x53, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x3d, 0x0a, 0x05, 0x52,
	0x65, 0x73, 0x65, 0x74, 0x12, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x73,
	0x65, 0x74, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x54, 0x79,
	0x70, 0x65, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x42, 0x0a, 0x0d, 0x4c, 0x6f,
	0x6f, 0x6b, 0x75, 0x70, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x1d, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x54, 0x79, 0x70, 0x65, 0x1a, 0x10, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x30, 0x01, 0x12, 0x45,
	0x0a, 0x15, 0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70,
	0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x1a, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x68,
	0x75, 0x6e, 0x6b, 0x30, 0x01, 0x12, 0x48, 0x0a, 0x10, 0x4e, 0x6f, 0x6e, 0x4c, 0x6f, 0x6f, 0x6b,
	0x75, 0x70, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x20, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x4e, 0x6f, 0x6e, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x50, 0x72, 0x6f, 0x66, 0x69,
	0x6c, 0x65, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x54, 0x79, 0x70, 0x65, 0x1a, 0x10, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x30, 0x01, 0x12,
	0x4b, 0x0a, 0x14, 0x53, 0x74, 0x6f, 0x70, 0x4e, 0x6f, 0x6e, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70,
	0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x4e, 0x6f, 0x6e, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x4b, 0x0a, 0x18,
	0x44, 0x6f, 0x77, 0x6e, 0x6c, 0x6f, 0x61, 0x64, 0x4e, 0x6f, 0x6e, 0x4c, 0x6f, 0x6f, 0x6b, 0x75,
	0x70, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x4e, 0x6f, 0x6e, 0x4c, 0x6f, 0x6f, 0x6b, 0x75, 0x70, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x1a, 0x10, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x46, 0x69,
	0x6c, 0x65, 0x43, 0x68, 0x75, 0x6e, 0x6b, 0x30, 0x01, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_profile_proto_rawDescOnce sync.Once
	file_profile_proto_rawDescData = file_profile_proto_rawDesc
)

func file_profile_proto_rawDescGZIP() []byte {
	file_profile_proto_rawDescOnce.Do(func() {
		file_profile_proto_rawDescData = protoimpl.X.CompressGZIP(file_profile_proto_rawDescData)
	})
	return file_profile_proto_rawDescData
}

var file_profile_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_profile_proto_goTypes = []interface{}{
	(ProfileVariable)(0),              // 0: proto.ProfileVariable
	(LookupProfile)(0),                // 1: proto.LookupProfile
	(NonLookupProfile)(0),             // 2: proto.NonLookupProfile
	(*FileChunk)(nil),                 // 3: proto.FileChunk
	(*StringType)(nil),                // 4: proto.StringType
	(*LookupProfileType)(nil),         // 5: proto.LookupProfileType
	(*NonLookupProfileType)(nil),      // 6: proto.NonLookupProfileType
	(*SetProfileInputType)(nil),       // 7: proto.SetProfileInputType
	(*ResetProfileInputType)(nil),     // 8: proto.ResetProfileInputType
	(*LookupProfileInputType)(nil),    // 9: proto.LookupProfileInputType
	(*NonLookupProfileInputType)(nil), // 10: proto.NonLookupProfileInputType
	(*duration.Duration)(nil),         // 11: google.protobuf.Duration
	(*empty.Empty)(nil),               // 12: google.protobuf.Empty
}
var file_profile_proto_depIdxs = []int32{
	1,  // 0: proto.LookupProfileType.Profile:type_name -> proto.LookupProfile
	2,  // 1: proto.NonLookupProfileType.Profile:type_name -> proto.NonLookupProfile
	0,  // 2: proto.SetProfileInputType.Variable:type_name -> proto.ProfileVariable
	0,  // 3: proto.ResetProfileInputType.Variable:type_name -> proto.ProfileVariable
	1,  // 4: proto.LookupProfileInputType.ProfileType:type_name -> proto.LookupProfile
	2,  // 5: proto.NonLookupProfileInputType.ProfileType:type_name -> proto.NonLookupProfile
	11, // 6: proto.NonLookupProfileInputType.Duration:type_name -> google.protobuf.Duration
	12, // 7: proto.ProfileService.Ping:input_type -> google.protobuf.Empty
	12, // 8: proto.ProfileService.ClearProfileCache:input_type -> google.protobuf.Empty
	7,  // 9: proto.ProfileService.Set:input_type -> proto.SetProfileInputType
	8,  // 10: proto.ProfileService.Reset:input_type -> proto.ResetProfileInputType
	9,  // 11: proto.ProfileService.LookupProfile:input_type -> proto.LookupProfileInputType
	5,  // 12: proto.ProfileService.DownloadLookupProfile:input_type -> proto.LookupProfileType
	10, // 13: proto.ProfileService.NonLookupProfile:input_type -> proto.NonLookupProfileInputType
	6,  // 14: proto.ProfileService.StopNonLookupProfile:input_type -> proto.NonLookupProfileType
	6,  // 15: proto.ProfileService.DownloadNonLookupProfile:input_type -> proto.NonLookupProfileType
	4,  // 16: proto.ProfileService.Ping:output_type -> proto.StringType
	12, // 17: proto.ProfileService.ClearProfileCache:output_type -> google.protobuf.Empty
	12, // 18: proto.ProfileService.Set:output_type -> google.protobuf.Empty
	12, // 19: proto.ProfileService.Reset:output_type -> google.protobuf.Empty
	3,  // 20: proto.ProfileService.LookupProfile:output_type -> proto.FileChunk
	3,  // 21: proto.ProfileService.DownloadLookupProfile:output_type -> proto.FileChunk
	3,  // 22: proto.ProfileService.NonLookupProfile:output_type -> proto.FileChunk
	12, // 23: proto.ProfileService.StopNonLookupProfile:output_type -> google.protobuf.Empty
	3,  // 24: proto.ProfileService.DownloadNonLookupProfile:output_type -> proto.FileChunk
	16, // [16:25] is the sub-list for method output_type
	7,  // [7:16] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_profile_proto_init() }
func file_profile_proto_init() {
	if File_profile_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_profile_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileChunk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_profile_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_profile_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookupProfileType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_profile_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NonLookupProfileType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_profile_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetProfileInputType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_profile_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResetProfileInputType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_profile_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LookupProfileInputType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_profile_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NonLookupProfileInputType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_profile_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_profile_proto_goTypes,
		DependencyIndexes: file_profile_proto_depIdxs,
		EnumInfos:         file_profile_proto_enumTypes,
		MessageInfos:      file_profile_proto_msgTypes,
	}.Build()
	File_profile_proto = out.File
	file_profile_proto_rawDesc = nil
	file_profile_proto_goTypes = nil
	file_profile_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ProfileServiceClient is the client API for ProfileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProfileServiceClient interface {
	Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*StringType, error)
	ClearProfileCache(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	Set(ctx context.Context, in *SetProfileInputType, opts ...grpc.CallOption) (*empty.Empty, error)
	Reset(ctx context.Context, in *ResetProfileInputType, opts ...grpc.CallOption) (*empty.Empty, error)
	LookupProfile(ctx context.Context, in *LookupProfileInputType, opts ...grpc.CallOption) (ProfileService_LookupProfileClient, error)
	DownloadLookupProfile(ctx context.Context, in *LookupProfileType, opts ...grpc.CallOption) (ProfileService_DownloadLookupProfileClient, error)
	NonLookupProfile(ctx context.Context, in *NonLookupProfileInputType, opts ...grpc.CallOption) (ProfileService_NonLookupProfileClient, error)
	StopNonLookupProfile(ctx context.Context, in *NonLookupProfileType, opts ...grpc.CallOption) (*empty.Empty, error)
	DownloadNonLookupProfile(ctx context.Context, in *NonLookupProfileType, opts ...grpc.CallOption) (ProfileService_DownloadNonLookupProfileClient, error)
}

type profileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProfileServiceClient(cc grpc.ClientConnInterface) ProfileServiceClient {
	return &profileServiceClient{cc}
}

func (c *profileServiceClient) Ping(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*StringType, error) {
	out := new(StringType)
	err := c.cc.Invoke(ctx, "/proto.ProfileService/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) ClearProfileCache(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/proto.ProfileService/ClearProfileCache", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) Set(ctx context.Context, in *SetProfileInputType, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/proto.ProfileService/Set", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) Reset(ctx context.Context, in *ResetProfileInputType, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/proto.ProfileService/Reset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) LookupProfile(ctx context.Context, in *LookupProfileInputType, opts ...grpc.CallOption) (ProfileService_LookupProfileClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ProfileService_serviceDesc.Streams[0], "/proto.ProfileService/LookupProfile", opts...)
	if err != nil {
		return nil, err
	}
	x := &profileServiceLookupProfileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ProfileService_LookupProfileClient interface {
	Recv() (*FileChunk, error)
	grpc.ClientStream
}

type profileServiceLookupProfileClient struct {
	grpc.ClientStream
}

func (x *profileServiceLookupProfileClient) Recv() (*FileChunk, error) {
	m := new(FileChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *profileServiceClient) DownloadLookupProfile(ctx context.Context, in *LookupProfileType, opts ...grpc.CallOption) (ProfileService_DownloadLookupProfileClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ProfileService_serviceDesc.Streams[1], "/proto.ProfileService/DownloadLookupProfile", opts...)
	if err != nil {
		return nil, err
	}
	x := &profileServiceDownloadLookupProfileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ProfileService_DownloadLookupProfileClient interface {
	Recv() (*FileChunk, error)
	grpc.ClientStream
}

type profileServiceDownloadLookupProfileClient struct {
	grpc.ClientStream
}

func (x *profileServiceDownloadLookupProfileClient) Recv() (*FileChunk, error) {
	m := new(FileChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *profileServiceClient) NonLookupProfile(ctx context.Context, in *NonLookupProfileInputType, opts ...grpc.CallOption) (ProfileService_NonLookupProfileClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ProfileService_serviceDesc.Streams[2], "/proto.ProfileService/NonLookupProfile", opts...)
	if err != nil {
		return nil, err
	}
	x := &profileServiceNonLookupProfileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ProfileService_NonLookupProfileClient interface {
	Recv() (*FileChunk, error)
	grpc.ClientStream
}

type profileServiceNonLookupProfileClient struct {
	grpc.ClientStream
}

func (x *profileServiceNonLookupProfileClient) Recv() (*FileChunk, error) {
	m := new(FileChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *profileServiceClient) StopNonLookupProfile(ctx context.Context, in *NonLookupProfileType, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/proto.ProfileService/StopNonLookupProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *profileServiceClient) DownloadNonLookupProfile(ctx context.Context, in *NonLookupProfileType, opts ...grpc.CallOption) (ProfileService_DownloadNonLookupProfileClient, error) {
	stream, err := c.cc.NewStream(ctx, &_ProfileService_serviceDesc.Streams[3], "/proto.ProfileService/DownloadNonLookupProfile", opts...)
	if err != nil {
		return nil, err
	}
	x := &profileServiceDownloadNonLookupProfileClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ProfileService_DownloadNonLookupProfileClient interface {
	Recv() (*FileChunk, error)
	grpc.ClientStream
}

type profileServiceDownloadNonLookupProfileClient struct {
	grpc.ClientStream
}

func (x *profileServiceDownloadNonLookupProfileClient) Recv() (*FileChunk, error) {
	m := new(FileChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ProfileServiceServer is the server API for ProfileService service.
type ProfileServiceServer interface {
	Ping(context.Context, *empty.Empty) (*StringType, error)
	ClearProfileCache(context.Context, *empty.Empty) (*empty.Empty, error)
	Set(context.Context, *SetProfileInputType) (*empty.Empty, error)
	Reset(context.Context, *ResetProfileInputType) (*empty.Empty, error)
	LookupProfile(*LookupProfileInputType, ProfileService_LookupProfileServer) error
	DownloadLookupProfile(*LookupProfileType, ProfileService_DownloadLookupProfileServer) error
	NonLookupProfile(*NonLookupProfileInputType, ProfileService_NonLookupProfileServer) error
	StopNonLookupProfile(context.Context, *NonLookupProfileType) (*empty.Empty, error)
	DownloadNonLookupProfile(*NonLookupProfileType, ProfileService_DownloadNonLookupProfileServer) error
}

// UnimplementedProfileServiceServer can be embedded to have forward compatible implementations.
type UnimplementedProfileServiceServer struct {
}

func (*UnimplementedProfileServiceServer) Ping(context.Context, *empty.Empty) (*StringType, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (*UnimplementedProfileServiceServer) ClearProfileCache(context.Context, *empty.Empty) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearProfileCache not implemented")
}
func (*UnimplementedProfileServiceServer) Set(context.Context, *SetProfileInputType) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (*UnimplementedProfileServiceServer) Reset(context.Context, *ResetProfileInputType) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reset not implemented")
}
func (*UnimplementedProfileServiceServer) LookupProfile(*LookupProfileInputType, ProfileService_LookupProfileServer) error {
	return status.Errorf(codes.Unimplemented, "method LookupProfile not implemented")
}
func (*UnimplementedProfileServiceServer) DownloadLookupProfile(*LookupProfileType, ProfileService_DownloadLookupProfileServer) error {
	return status.Errorf(codes.Unimplemented, "method DownloadLookupProfile not implemented")
}
func (*UnimplementedProfileServiceServer) NonLookupProfile(*NonLookupProfileInputType, ProfileService_NonLookupProfileServer) error {
	return status.Errorf(codes.Unimplemented, "method NonLookupProfile not implemented")
}
func (*UnimplementedProfileServiceServer) StopNonLookupProfile(context.Context, *NonLookupProfileType) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopNonLookupProfile not implemented")
}
func (*UnimplementedProfileServiceServer) DownloadNonLookupProfile(*NonLookupProfileType, ProfileService_DownloadNonLookupProfileServer) error {
	return status.Errorf(codes.Unimplemented, "method DownloadNonLookupProfile not implemented")
}

func RegisterProfileServiceServer(s *grpc.Server, srv ProfileServiceServer) {
	s.RegisterService(&_ProfileService_serviceDesc, srv)
}

func _ProfileService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProfileService/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).Ping(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_ClearProfileCache_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).ClearProfileCache(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProfileService/ClearProfileCache",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).ClearProfileCache(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetProfileInputType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProfileService/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).Set(ctx, req.(*SetProfileInputType))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_Reset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetProfileInputType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).Reset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProfileService/Reset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).Reset(ctx, req.(*ResetProfileInputType))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_LookupProfile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LookupProfileInputType)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProfileServiceServer).LookupProfile(m, &profileServiceLookupProfileServer{stream})
}

type ProfileService_LookupProfileServer interface {
	Send(*FileChunk) error
	grpc.ServerStream
}

type profileServiceLookupProfileServer struct {
	grpc.ServerStream
}

func (x *profileServiceLookupProfileServer) Send(m *FileChunk) error {
	return x.ServerStream.SendMsg(m)
}

func _ProfileService_DownloadLookupProfile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LookupProfileType)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProfileServiceServer).DownloadLookupProfile(m, &profileServiceDownloadLookupProfileServer{stream})
}

type ProfileService_DownloadLookupProfileServer interface {
	Send(*FileChunk) error
	grpc.ServerStream
}

type profileServiceDownloadLookupProfileServer struct {
	grpc.ServerStream
}

func (x *profileServiceDownloadLookupProfileServer) Send(m *FileChunk) error {
	return x.ServerStream.SendMsg(m)
}

func _ProfileService_NonLookupProfile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NonLookupProfileInputType)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProfileServiceServer).NonLookupProfile(m, &profileServiceNonLookupProfileServer{stream})
}

type ProfileService_NonLookupProfileServer interface {
	Send(*FileChunk) error
	grpc.ServerStream
}

type profileServiceNonLookupProfileServer struct {
	grpc.ServerStream
}

func (x *profileServiceNonLookupProfileServer) Send(m *FileChunk) error {
	return x.ServerStream.SendMsg(m)
}

func _ProfileService_StopNonLookupProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NonLookupProfileType)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfileServiceServer).StopNonLookupProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.ProfileService/StopNonLookupProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfileServiceServer).StopNonLookupProfile(ctx, req.(*NonLookupProfileType))
	}
	return interceptor(ctx, in, info, handler)
}

func _ProfileService_DownloadNonLookupProfile_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(NonLookupProfileType)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ProfileServiceServer).DownloadNonLookupProfile(m, &profileServiceDownloadNonLookupProfileServer{stream})
}

type ProfileService_DownloadNonLookupProfileServer interface {
	Send(*FileChunk) error
	grpc.ServerStream
}

type profileServiceDownloadNonLookupProfileServer struct {
	grpc.ServerStream
}

func (x *profileServiceDownloadNonLookupProfileServer) Send(m *FileChunk) error {
	return x.ServerStream.SendMsg(m)
}

var _ProfileService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ProfileService",
	HandlerType: (*ProfileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _ProfileService_Ping_Handler,
		},
		{
			MethodName: "ClearProfileCache",
			Handler:    _ProfileService_ClearProfileCache_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _ProfileService_Set_Handler,
		},
		{
			MethodName: "Reset",
			Handler:    _ProfileService_Reset_Handler,
		},
		{
			MethodName: "StopNonLookupProfile",
			Handler:    _ProfileService_StopNonLookupProfile_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "LookupProfile",
			Handler:       _ProfileService_LookupProfile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DownloadLookupProfile",
			Handler:       _ProfileService_DownloadLookupProfile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "NonLookupProfile",
			Handler:       _ProfileService_NonLookupProfile_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DownloadNonLookupProfile",
			Handler:       _ProfileService_DownloadNonLookupProfile_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "profile.proto",
}
